### PR TITLE
Feat: adding support for pnpm

### PR DESCRIPTION
**Pull request by ramykl**
**SEMVER Update Type:**
- [ ] Major
- [ ] Minor
- [ ] Patch

I would assume it is just a patch or minor as it doesn't change any of defaults or the normal behaviours, just adds an optional extra feature of pnpm as a package manager.

## Description:

- add support for `pnpm` as a package manager
- fix `test-deploy.yml` `node/test` and `node/run` steps to find the correct lock files for the corresponding `pkg-manager` by removing the other ones

## Motivation:

 **Closes Issues:**
- https://github.com/CircleCI-Public/node-orb/issues/167
- https://github.com/CircleCI-Public/node-orb/issues/89

Also shows how someone could do this:
- https://github.com/CircleCI-Public/node-orb/issues/194
## Checklist:

- [x] All new jobs, commands, executors, parameters have descriptions.
- [x] Usage Example version numbers have been updated.
- [ ] Changelog has been updated.

### CODE REVIEW

**Comment by ramykl** [comment]
Not sure what I need to do to get the circleCI checks to run here or if it requires a review to trigger them.
I'm not sure the uninstall steps are correct for `pnpm` as I just took the `yarn` steps. I didn't see a test for those. Possibly should just be simplified to assume pnpm was installed via `npm install -g pnpm`.

It would be great to have a bit more documentation about contributing and how to get all the checks to run.

**Comment by ramykl** [comment]
@KyleTryon Any help on getting these final tests to run? Or what else I can do to get this PR to be processed?

**Comment by ramykl** [comment]
Here it is against main on my fork with the checks successful and complete https://github.com/ramykl/node-orb/pull/1

**Comment by jennifer-shehane** [comment]
@KyleTryon Any chance to get a review on this? This would help with support on the cypress orb as well. https://github.com/cypress-io/circleci-orb/pull/445

**Comment by KyleTryon** [comment]
Hello all 👋  I just got back from vacation and ran your tests, all looks good! We're going to add this shortly, we just want to try to merge in some fixes before adding this feature. I'll update here shortly. Thanks again!

**Comment by ramykl** [comment]
Any updates here?

**Comment by KyleTryon** [comment]
> Any updates here? @KyleTryon 

Sorry, I am no longer a member of CircleCI.

**Comment by ramykl** [comment]
> Sorry, I am no longer a member of CircleCI.

Sorry to hear that.

**Comment by ramykl** [comment]
@brentmmarks Any chance of a review/update?

**Comment by ramykl** [comment]
@EricRibeiro any chance of a review/update? Would be great to get this merged

**Comment by EricRibeiro** [comment]
> @EricRibeiro any chance of a review/update? Would be great to get this merged

I'm sorry, but I'm no longer working at CircleCI. It would be best to reach out to their support team for assistance with this pull request.

**Comment by ramykl** [comment]
@brentmmarks Any chance of a review and merge please?

**Comment by ashfaqnisar** [comment]
@felicianotech any chance you could review this ?

**Comment by CodeBooster97** [comment]
Any news?

**Comment by ramykl** [comment]
@ashfaqnisar or @felicianotech any news?

**Comment by AlvesJorge** [comment]
very thankful for your resilience @ramykl 
Also it's somewhat funny that the only employees from circleci to respond are the ones that are no longer employees.

Bump

**Comment by ramykl** [comment]
@marboledacci any chance of a review?

**Review by marboledacci — APPROVED** [review]

**Pull request merged**
