### PR TITLE
fix!: do not fall back to source builds of Node.js

### LINKED ISSUE #183: Prevent nvm from falling back to building from source
We've hit an issue that if the binary download fails, then nvm will [fall back to building Node from source](https://github.com/nvm-sh/nvm/blob/edacf8275e3bef4a80971625ed89df13a9af427c/nvm.sh#L2111). This takes a _long_ time and burns through credits, when it'd be quicker to just fail and try the job again.

nvm does support the [`-b` option for installs](https://github.com/nvm-sh/nvm/blob/edacf8275e3bef4a80971625ed89df13a9af427c/nvm.sh#L2845) so that it will only install from binary, and skip installing from source. It would be nice if this orb either set this option all the time, or provided some way to opt in to setting it.

Thanks!

### PR DESCRIPTION
**Pull request by dsanders11**
Closes #183.

Opening a PR to get the ball rolling on this, been bit a few times now by this.

cc @KyleTryon

### CODE REVIEW

**Comment by olleolleolle** [comment]
Oh, I'd like this, even if it were an option I had to pass to the node-orb settings.

**Comment by olleolleolle** [comment]
Oh, just _now_ I wanted this feature, the Node 20 build was just too long for the 10-minute window that I had.

cc @KyleTryon Do you know whether this is something planned or anything?

**Comment by KyleTryon** [comment]
> Oh, just _now_ I wanted this feature, the Node 20 build was just too long for the 10-minute window that I had.
> 
> cc @KyleTryon Do you know whether this is something planned or anything?

I am no longer an employee of CircleCI. Sorry, I have no insight into anything planned in this org any longer.

**Comment by olleolleolle** [comment]
@KyleTryon Thanks for responding, and sorry to notify you about this. May your weekend be excellent.

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/node?version=dev:9ba92079fdaa31fabfb3309ae4cd63a6975439f0

**Review by marboledacci — APPROVED** [review]

**Pull request merged**
