### PR TITLE
Only install nvm when needed. [semver:patch]

### PR DESCRIPTION
**Pull request by felicianotech**
Fixes: #62 

Brought about by @gmemstr and ARM testing.

I'm not sure about the semver level. Open to feedback.

### CODE REVIEW

**Comment by dsayling** [comment]
> I'm not sure about the semver level. Open to feedback.

Does it fail to install over an existing version in a docker executor too? If that's the case, I agree with patch.

**Comment by felicianotech** [comment]
As far as I know, this was strictly an issue when using the orb with the Linux machine image.

**Comment by KyleTryon** [comment]
Patch seems fine to me.

**Review by KyleTryon — APPROVED** [review]
Smart change 👍

**Pull request merged**
