### PR TITLE
Add quickstart jobs with examples

### PR DESCRIPTION
**Pull request by glenjamin**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

This was prompted by a conversation in slack, about how easy we could make onboarding a new NodeJS project.

### Description

* Adds `npm-ci`, which installs dependencies in the [way npm recommends for CI](https://docs.npmjs.com/cli/ci)
* Adds `run` job, which does checkout, dependencies, then runs whatever you tell it to
* Adds `test` job, which does checkout, dependencies, then runs your tests

### CODE REVIEW

**Comment by eddiewebb** [comment]
@KyleTryon / @felicianotech / @lokst - can any of you review this? Glenn's contributions fit squarely into Q2 and Q3 objectives for this team!

**Comment by eddiewebb** [comment]
@glenjamin - only cursory review, but it looks like this will need new examples too right?

**Comment by glenjamin** [comment]
> @glenjamin - only cursory review, but it looks like this will need new examples too right?

Yep, this is more of a rough demo than a finished product. 

This was motivated by a suggestion in slack https://circleci.slack.com/archives/C5S301CD6/p1564683033039600?thread_ts=1564591979.016500&cid=C5S301CD6 - and I wanted to try it out and see how well it worked.

Here's one of my OSS projects using it: https://circleci.com/gh/glenjamin/transit-immutable-js/3

**Comment by lokst** [comment]
@eddiewebb @glenjamin Sure I'll take a look tomorrow!

**Comment by glenjamin** [comment]
Is this sort of approach something we want to use on the other languages too?

My main concern with merging and publicizing something like this is that once have one in, we either need to do all of the others very similarly, or make "breaking" changes here if better patterns emerge.

Having me pick the pattern for you on a whim seems like it might not be the ideal approach 😁

**Comment by KyleTryon** [comment]
@felicianotech and I were talking about this yesterday. Personally, I am ok with adding this now but recognize that we want to do a much more general overhaul to all language orbs. 

This is a part of [internal] https://circleci.atlassian.net/browse/CIRCLE-20006

It might be some time before the practices for language orbs are defined if we want to add this in the meantime. I think most language orbs will end up mostly re-written.

**Comment by glenjamin** [comment]
Ok, I'm pretty happy with how this looks now.

I've added examples for some common use-cases.



> and re-architect the jobs to invoke sub-commands (that handle caching, test results and other common concerns)

Would that be blocking, or is that something we can do in future PRs?

**Pull request merged**
