### PR TITLE
[semver:minor] include arch in cache keys

### PR DESCRIPTION
**Pull request by adkenyon**
I was having issues with this orb when using caching between different architectures. Including the `{{ arch }}` interpolation in the cache key

### CODE REVIEW

**Comment by adkenyon** [comment]
@gmemstr @KyleTryon ^^

**Comment by day-me-an** [comment]
Any update on this? I'm encountering the same issue: https://support.circleci.com/hc/en-us/articles/360056920051--Error-untarring-cache-when-running-a-macOS-job

**Comment by adkenyon** [comment]
@day-me-an My temporary solution is to pass the arch through the cache-version parameter

```
- node/install-packages:
      pkg-manager: yarn
      include-branch-in-cache-key: false
      cache-version: arch-{{ arch }}
```

**Comment by KyleTryon** [comment]
Hey folks, sorry for the delay. We'll be getting to this very shortly now.

**Review by KyleTryon — APPROVED** [review]
Great addition 👍 . Thanks for adding this.

**Pull request merged**
