### PR TITLE
Setting Node version with nvm under machine images [semver:patch]

### PR DESCRIPTION
**Pull request by felicianotech**
This should be rebased, re-run (and should pass) after #72 is merged.

### CODE REVIEW

**Comment by dsayling** [comment]
any reason to not include this change in #73?

**Comment by felicianotech** [comment]
Just [PR etiquette](https://fagnerbrack.medium.com/one-pull-request-one-concern-e84a27dfe9f1) that I like to follow. It's good practice.

For example, Gabe wasn't even sure if we should add this test. This allows us to easily ignore or revert this change without touching #72.

**Comment by dsayling** [comment]
> Just [PR etiquette](https://fagnerbrack.medium.com/one-pull-request-one-concern-e84a27dfe9f1) that I like to follow. It's good practice.
> 
> For example, Gabe wasn't even sure if we should add this test. This allows us to easily ignore or revert this change without touching #72.

I agree with keeping the changes small, but since this test validates the change in #72, IMHO, I would include it.

**Comment by KyleTryon** [comment]
I also see the etiquette but feel as though it makes more sense to combine these. Though as the other PR shouldnt have any negative effects, I could take this either way. But as these two changes are related to the same single issue, I'd vote to combine.

**Comment by dsayling** [comment]
@felicianotech looks like #72 did not resolve #62

**Comment by gmemstr** [comment]
I'm not 100% on _why_ this is yet but it looks like the nvm version isn't being correctly set in the environment for whatever reason, despite installing fine.

**Comment by felicianotech** [comment]
@gmemstr @dsayling Can either of you point me to an example of where there is still an issue with the Node.js orb v4.2.0 doesn't work right?

**Comment by felicianotech** [comment]
I'm still learning how the embedded scripts work. Where does this grep error come from? I don't see where we use it. https://app.circleci.com/pipelines/github/CircleCI-Public/node-orb/687/workflows/4214ce53-c75d-4673-8aeb-a3aec12f1f95/jobs/4459

**Review by KyleTryon — APPROVED** [review]

**Pull request merged**
